# target land position in WGS84 coordinates and calculated shift in Body NED coordinate system.
uint64 timestamp			# Timestamp (microseconds since system boot)

float32 x				# x offset to target in vehicle NED frame in m
float32 y				# y offset to target in vehicle NED frame in m
float32 z				# z offset to target in vehicle NED frame in m

float32 yaw				# yaw angle to target in vehicle NED frame
